### ISSUE TITLE
No display on Mac

### ISSUE THREAD

**Issue by ghost** [akshayKMR/hogwatch#10]
After some difficulty getting all of the requirements installed:
I needed to set MACOSX_DEPLOYMENT_TARGET=10.11 to get pyobjc dependencies through.
I managed to get it to run (both in standalone window and in Chrome).
However, no graphs and everything is 0 kB or 0 kB/s.
Also see following log errors on console.

sudo ./hogwatch server
/Users/GitHubStuff/hogwatch/application/server/static/
[]
'transfer_rate'

---

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users//anaconda/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/Users//anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users//GitHubStuff/hogwatch/application/server/watchdogs/nethogs.py", line 44, in watch_transfer
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, bufsize=1)
  File "/Users/anaconda/lib/python2.7/subprocess.py", line 710, in __init**
    errread, errwrite)
  File "/Users/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

[]
'transfer_amount'

---

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/anaconda/lib/python2.7/threading.py", line 801, in **bootstrap_inner
    self.run()
  File "/Users/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/Users/GitHubStuff/hogwatch/application/server/watchdogs/nethogs.py", line 44, in watch_transfer
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, bufsize=1)
  File "/Users/anaconda/lib/python2.7/subprocess.py", line 710, in __init**
    errread, errwrite)
  File "/Users/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by akshaykmr** [comment]
You need to have nethogs installed as listed in the requirements. It is a commandline utility that provides all the information. However for now it will list connections only as mapping to process is currently not available for OSX. [Link for nethogs](https://github.com/raboof/nethogs)

**Comment by ghost** [comment]
Thanks! It was installed but not in my path
