### ISSUE TITLE
ImportError: No module named hogwatch.server.web_service

### ISSUE THREAD

**Issue by zerinoid** [akshayKMR/hogwatch#19]
I'm getting this error when running the program.

```
Traceback (most recent call last):
  File "/home/zerinol/.local/bin/hogwatch", line 7, in <module>
    from hogwatch.server.web_service import app_server
ImportError: No module named hogwatch.server.web_service
```
and if I try it with sudo

`sudo: hogwatch: command not found`
which is even weirder.

I'm on ubuntu 18.04 and /usr/bin/python is symlinked to python2.7

**Comment by zerinoid** [comment]
tryied symlinking to 3.6 and the result is

```
  File "/home/zerinol/.local/bin/hogwatch", line 10
    print "Hit ctrl-c to exit"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Hit ctrl-c to exit")?
```
