### ISSUE TITLE
Pip install fails in virtualenv

### ISSUE THREAD

**Issue by kseistrup** [akshayKMR/hogwatch#3]
``` pytb
$ cd ~/.local/lib/venv2
$ virtualenv2 hogwatch
$ source hogwatch/bin/activate
$ pip install hogwatch
Collecting hogwatch
  Downloading hogwatch-0.0.2.tar.gz (521kB)
    100% |████████████████████████████████| 522kB 1.3MB/s
    Complete output from command python setup.py egg_info:

    Installed /tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.1.3
    Downloading https://pypi.python.org/packages/41/68/e985491370cc44a063ac5c70232bf72d7675fa7539a86fa7fa08257bda05/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2
    Processing pypandoc-1.1.3.zip
    Writing /tmp/user/3253/easy_install-iTMSpd/pypandoc-1.1.3/setup.cfg
    Running pypandoc-1.1.3/setup.py -q bdist_egg --dist-dir /tmp/user/3253/easy_install-iTMSpd/pypandoc-1.1.3/egg-dist-tmp-BcZUqL
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    Patching wheel building...
    Making sure that wheel is platform specific...
    creating /tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg
    Extracting pypandoc-1.1.3-py2.7.egg to /tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs

    Installed /tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/user/3253/pip-build-dd0Opq/hogwatch/setup.py", line 38, in <module>
        'netifaces'
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/kseistrup/.local/lib/venv2/hogwatch/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/kseistrup/.local/lib/venv2/hogwatch/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/tmp/user/3253/pip-build-dd0Opq/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 68, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/user/3253/pip-build-dd0Opq/hogwatch/
```

This does seem to be an error with pandoc, but pandoc has been installed systemwide and is used by other modules, so somehow hogwatch is involved.

Python 2.7.11 on Linux.

**Comment by scancmdr** [comment]
I can confirm a similar issue on Python 2.7.6 Ubuntu 14.04.4 LTS

```
Installed /tmp/pip_build_jay/hogwatch/pypandoc-1.1.3-py2.7.egg
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_jay/hogwatch/setup.py", line 38, in <module>
    'netifaces'
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
    ep.load()(self, ep.name, value)
  File "/tmp/pip_build_jay/hogwatch/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
    output = pypandoc.convert(markdown_filename, 'rst')
  File "/tmp/pip_build_jay/hogwatch/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 50, in convert
    outputfile=outputfile, filters=filters)
  File "/tmp/pip_build_jay/hogwatch/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 68, in _convert
    raise RuntimeError('Missing format!')
RuntimeError: Missing format!
```

**Comment by insanoid** [comment]
Same issue happens on OS X 10.11 (15A284) and Python 2.7.10.

**Comment by previousdeveloper** [comment]
+1

**Comment by Qu4tro** [comment]
Same issue on updated Arch Linux.

**Comment by matan129** [comment]
Same here, Python 2.7.11

**Comment by yask123** [comment]
I tested this on OS X:

```
$ virtualenv -p `which python`  yourenv
$ source yourenv/bin/activate
$ pip install hogwatch
```

Failed with the error mentioned above.

The I cloned your repo and manually installed your module in the same virtualenv and it installed successfully.

I think you need to update your module in PyPy

**Comment by pmontrasio** [comment]
Same problem in a fresh install of Ubuntu 16.04

```
$ python --version
Python 2.7.11+

$ pip --version
pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

```
$ pip install hogwatch
Collecting hogwatch
  Using cached hogwatch-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-RnUljl/hogwatch/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.1.3
    Downloading https://pypi.python.org/packages/41/68/e985491370cc44a063ac5c70232bf72d7675fa7539a86fa7fa08257bda05/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2
    Processing pypandoc-1.1.3.zip
    Writing /tmp/easy_install-FtoRol/pypandoc-1.1.3/setup.cfg
    Running pypandoc-1.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-FtoRol/pypandoc-1.1.3/egg-dist-tmp-FxLOjy
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    Patching wheel building...
    Making sure that wheel is platform specific...
    creating /tmp/pip-build-RnUljl/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg
    Extracting pypandoc-1.1.3-py2.7.egg to /tmp/pip-build-RnUljl/hogwatch/.eggs

    Installed /tmp/pip-build-RnUljl/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-RnUljl/hogwatch/setup.py", line 38, in <module>
        'netifaces'
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/me/.local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/me/.local/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-RnUljl/hogwatch/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-RnUljl/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/tmp/pip-build-RnUljl/hogwatch/.eggs/pypandoc-1.1.3-py2.7.egg/pypandoc/__init__.py", line 68, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RnUljl/hogwatch/
```

**Comment by akshaykmr** [comment]
I just updated the package. install with:
 `pip install hogwatch --upgrade`

**Comment by nascob** [comment]
It still fails for me Python 2.7.10, OS X 10.11.3

```
Collecting pyobjc-framework-AVKit==3.1.1 (from pyobjc->pywebview->hogwatch)
  Using cached pyobjc-framework-AVKit-3.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-HEkkiN/pyobjc-framework-AVKit/setup.py", line 35, in <module>
        if fn.startswith('_AVKit')
      File "pyobjc_setup.py", line 496, in setup
        **k
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (pyobjc-core 2.5.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC), Requirement.parse('pyobjc-core>=3.1.1'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-HEkkiN/pyobjc-framework-AVKit/
```

**Comment by sahildua2305** [comment]
@akshayKMR works for Python 2.7.6 Ubuntu 14.04 now. Installation issue resolved. But shows nothing on running it. Blank sceen. No process, no logging. Seems like another issue.

**Comment by akshaykmr** [comment]
@sahildua2305 ensure that you are running it as `sudo hogwatch` root permission is needed for nethogs. 

```
(test) ➜  ~ hogwatch server 6433
/usr/local/lib/python2.7/dist-packages/application/server/static/
[]
'transfer_rate'
******************************************
You need to be root to run NetHogs!
[]
'transfer_amount'
******************************************
You need to be root to run NetHogs!
^C^Z
[1]  + 21511 suspended  hogwatch server 6433
(test) ➜  ~ sudo fuser -n tcp -k 6433
6433/tcp:            21511
[1]  + 21511 killed     hogwatch server 6433
(test) ➜  ~ sudo hogwatch            
/usr/local/lib/python2.7/dist-packages/application/server/static/
WARNING:webview.qt:PyQt4 is not found
WARNING:webview.qt:PyQt5 is not found
WARNING:webview:QT not found
INFO:geventwebsocket.handler:127.0.0.1 - - [2016-05-01 06:58:19] "GET /index.html HTTP/1.1" 200 8030 0.010382
INFO:geventwebsocket.handler:127.0.0.1 - - [2016-05-01 06:58:19] "GET /js/vue.js HTTP/1.1" 200 264955 0.000881
INFO:geventwebsocket.handler:127.0.0.1 - - [2016-05-01 06:58:19] "GET /css/css_reset.css HTTP/1.1" 200 1288 0.000483
INFO:geventwebsocket.handler:127.0.0.1 - - [2016-05-01 06:58:19] "GET /css/style.css HTTP/1.1" 200 11057 0.000473

```

<img width="994" alt="screen shot 2016-05-01 at 7 03 21 am" src="https://cloud.githubusercontent.com/assets/11945793/14939615/d5fdde5e-0f6b-11e6-862e-0e0b717de67e.png">

I did install it in a vm just now - elementary OS freya (based on ubuntu 14.04)

when you run the above command try running some internet application or `speedtest-cli` in a new terminal.

If it fails. try a different port e.g `sudo hogwatch server 6433`and open localhost:6433 in the web browser and see if there are any logs on the console.

@atanasbozhkov  I'll look into it.

**Comment by pmontrasio** [comment]
It works now. There are other two issues that I'll report separately.

**Comment by akshaykmr** [comment]
The package uses a pip module called pywebview for opening a webview window directly. Its easy to use but it sometimes doesn't display output as it would on a web browser such as chrome, moreover installing it requires some additional packages on some systems as reported by users. 
pywebview also downloads a lot of dependencies when installing on osx considering which I suggest  installing the following way 

`git clone https://github.com/akshayKMR/hogwatch.git`
`cd hogwatch`
now _remove_ pywebview from **requirements.txt** and comment it from **setup.py**
`pip install -r requirements.txt`
`sudo python setup.py install`
`sudo ./hogwatch server`
and access it on chrome localhost:6432

OS X users can try the **experimental** menubar as well. For instructions go to hogwatch/menubar/Readme.md 
note: hogwatch must be available in path
